POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "dionlaning@gmail.com",
    "password":"12345"
}

###
GET http://localhost:5000/introspect

###
DELETE http://localhost:5000/logout

###
GET http://localhost:5000/users

###
GET http://localhost:5000/users/57d919f7-eaaa-452a-b751-c65e979e8f15

###
POST http://localhost:5000/user
Content-Type: application/json

{
    "name" : "Dion Laning",
    "email" : "dionlaning@gmail.com",
    "password" : "12345",
    "confirmPassword" : "12345",
    "role" : "user"
}

###
PUT http://localhost:5000/users/57d919f7-eaaa-452a-b751-c65e979e8f15
Content-Type: application/json

{
    "name" : "Erick Hene",
    "email" : "djefrison@gmail.com",
    "password" : "12345",
    "confirmPassword" : "12345",
    "role" : "admin"
}

###
DELETE http://localhost:5000/users/57d919f7-eaaa-452a-b751-c65e979e8f15

###
GET http://localhost:5000/product

###
GET http://localhost:5000/product/56384942-6a9c-4b89-9742-ed94d8d5738c

###
POST http://localhost:5000/product
Content-Type: application/json

{
    "name":"Nasi",
    "price":3000
}

###
PUT http://localhost:5000/product/56384942-6a9c-4b89-9742-ed94d8d5738c
Content-Type: application/json

{
    "name":"Nabas",
    "price":30000
}

###
DELETE http://localhost:5000/product/f19e71e3-f579-4efa-991e-c2f6a8a97c70